# Generated by Django 3.2.4 on 2021-09-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210909_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_all_users', 'Can view all users'), ('can_view_itself_only', 'Can view itself only')]},
        ),
    ]
