version: '3.8'

services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment:
            - SECRET_KEY=hx76H%y6MGX6$$fEV9QdHXt&qqCJS2dX^ # django-insecure-p2nl$7sgbqq$mr$$#6y*#s=n@zzw@ihk1*xi-#!_+hplrvc=6&
            - DEBUG=1
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
    
    db:
        image: postgres:13
        environment:
            - POSTGRES_PASSWORD=adam
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data: