# Generated by Django 3.2.4 on 2021-06-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='is_private_person',
            field=models.BooleanField(default=False, verbose_name='Private person'),
        ),
    ]
