# Generated by Django 3.2.4 on 2021-06-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_is_private_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tax_number',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
    ]
