# Generated by Django 3.2.4 on 2021-07-01 13:50

from django.db import migrations, models
import documents.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0003_auto_20210629_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceiptNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grn', models.CharField(blank=True, max_length=11)),
                ('date', models.DateField()),
                ('print_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=models.SET(documents.models.get_deleted_vendor), related_name='goods_receipt_notes', to='partners.vendor')),
            ],
        ),
    ]
