# Generated by Django 3.2.4 on 2021-07-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='grn',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
