# Generated by Django 3.2.4 on 2021-07-07 08:42

from django.db import migrations, models
import documents.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20210629_1618'),
        ('documents', '0002_alter_goodsreceiptnote_grn'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDispatchNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gdn', models.CharField(blank=True, max_length=14)),
                ('date', models.DateField()),
                ('print_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=models.SET(documents.models.get_deleted_customer), related_name='goods_dispatch_notes', to='partners.vendor')),
            ],
        ),
    ]
