# Generated by Django 3.2.4 on 2021-07-07 08:53

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20210629_1618'),
        ('documents', '0003_goodsdispatchnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsdispatchnote',
            name='customer',
            field=models.ForeignKey(on_delete=models.SET(documents.models.get_deleted_customer), related_name='goods_dispatch_notes', to='partners.customer'),
        ),
    ]
