# Generated by Django 3.2.4 on 2021-08-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_goodsdispatchnote_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
