# Generated by Django 3.2.4 on 2021-08-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_goodsreceiptnote_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsdispatchnote',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='goods_dispatch_notes/'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='goods_receipt_notes/'),
        ),
    ]
