# Generated by Django 3.2.4 on 2021-06-30 09:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound')], default='IN', max_length=3)),
                ('transaction_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('gross_weight', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('tare_weight', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notes', models.TextField(max_length=255)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventories.material')),
            ],
        ),
    ]
