# Generated by Django 3.2.4 on 2021-07-02 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('inventories', '0003_alter_transaction_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='goods_receipt_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='documents.goodsreceiptnote'),
        ),
    ]
