# Generated by Django 3.2.4 on 2021-07-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0004_transaction_goods_receipt_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tare_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
