# Generated by Django 3.2.4 on 2021-07-07 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_goodsdispatchnote'),
        ('inventories', '0005_alter_transaction_tare_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='goods_dispatch_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='documents.goodsdispatchnote'),
        ),
    ]
